def DOCKER_REG = "docker.io/mmaheu/nostromo"
def DOCKER_USR = "mmaheu"
def DOCKER_TAG = "dev"
def DOCKER_PSW = "FireBox69"
def IMG_PULL_SECRET = "docker-reg-secret"
def HELM_REPO = "http://127.0.0.1:8879/charts"
def HELM_USR = "admin"
def HELM_PSW = "password"
